{
 "title": "YACE",
 "description": "Dashboard for the yet-another-cloudwatch-exporter(https://github.com/nerdswords/yet-another-cloudwatch-exporter) exporter scraping AWS resources.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_swap_usage_average",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "free storage space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 17 },
   "targets": [
    {
     "expr": "aws_rds_disk_queue_depth_average",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  { "title": "Lambda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "aws_lambda_invocations_average", "legendFormat": "{{dimension_FunctionName}}" }
   ]
  },
  {
   "title": "errors sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "aws_lambda_errors_average", "legendFormat": "{{dimension_FunctionName}}" }
   ]
  },
  {
   "title": "Duration(Execution time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aws_lambda_duration_average", "legendFormat": "{{dimension_FunctionName}}" }
   ]
  },
  { "title": "ECS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aws_ecs_cpuutilization_average", "legendFormat": "{{dimension_ClusterName}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_ecs_memory_utilization_average",
     "legendFormat": "{{dimension_ClusterName}}"
    }
   ]
  },
  { "title": "SQS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Approximate Number of Messages Delayed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average",
     "legendFormat": "{{dimension_QueueName}}"
    }
   ]
  },
  {
   "title": "Approximate Number of Messages not Visible",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average",
     "legendFormat": "{{dimension_QueueName}}"
    }
   ]
  },
  { "title": "Load Balancers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Active Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_applicationelb_target_response_time_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Active Flow Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Packets Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_packets_average",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  { "title": "SNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Number of notifications Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "aws_sns_number_of_notifications_failed_average",
     "legendFormat": "{{dimension_TopicName}}"
    }
   ]
  },
  { "title": "ElastiCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "aws_elasticache_cache_misses_average",
     "legendFormat": "{{dimension_CacheClusterId}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average",
     "legendFormat": "{{dimension_CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "aws_elasticache_evictions_average",
     "legendFormat": "{{dimension_CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_elasticache_freeable_memory_average",
     "legendFormat": "{{dimension_CacheClusterId}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_elasticache_swap_usage_average",
     "legendFormat": "{{dimension_CacheClusterId}}"
    }
   ]
  },
  { "title": "Elastic Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "JVM Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_es_jvmmemory_pressure_average",
     "legendFormat": "{{dimension_DomainName}}"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_free_storage_space_average",
     "legendFormat": "{{dimension_DomainName}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aws_es_cpuutilization_average", "legendFormat": "{{dimension_DomainName}}" }
   ]
  },
  {
   "title": "Cluster Status Red",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_es_cluster_status_red_maximum",
     "legendFormat": "{{dimension_DomainName}}"
    }
   ]
  },
  { "title": "Database Migration Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_dms_cpuutilization_average",
     "legendFormat": "{{dimension_ReplicationInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_dms_freeable_memory_average",
     "legendFormat": "{{dimension_ReplicationInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_dms_free_storage_space_average",
     "legendFormat": "{{dimension_ReplicationInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "CDC Latency Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_dms_cdclatency_source_average",
     "legendFormat": "{{dimension_ReplicationInstanceIdentifier}}-{{dimension_ReplicationTaskIdentifier}}"
    }
   ]
  },
  {
   "title": "CDC Latency Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_dms_cdclatency_target_average",
     "legendFormat": "{{dimension_ReplicationInstanceIdentifier}}-{{dimension_ReplicationTaskIdentifier}}"
    }
   ]
  },
  { "title": "S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Number of Objects Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  }
 ]
}