{
 "title": "External DNS",
 "description": "External DNS",
 "tags": [
  "core-services",
  "external-dns"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "DNS Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Verified A Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_a_records"
    }
   ]
  },
  {
   "title": "Verified CNAME Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_cname_records"
    }
   ]
  },
  {
   "title": "Registry Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total"
    }
   ]
  },
  {
   "title": "Last Sync Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_last_sync_timestamp * 1000"
    }
   ]
  },
  { "title": "Operations & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Source & Registry Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(external_dns_source_errors_total[5m])",
     "legendFormat": "Source Errors"
    },
    {
     "expr": "rate(external_dns_registry_errors_total[5m])",
     "legendFormat": "Registry Errors"
    }
   ]
  },
  {
   "title": "DNS Record Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(external_dns_registry_endpoints_total[5m]))",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}